### ISSUE TITLE
Is  there some problem with the configuration or version of arquillian?

### ISSUE THREAD

**Issue by joedayz** [javaee-samples/javaee7-samples#285]
Hi guys

I am getting this error in a new fresh installation. 

Test set: org.javaee7.batch.chunk.checkpoint.BatchChunkCheckpointTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.02 sec <<< FAILURE! - in org.javaee7.batch.chunk.checkpoint.BatchChunkCheckpointTest
org.javaee7.batch.chunk.checkpoint.BatchChunkCheckpointTest  Time elapsed: 5.019 sec  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not start container
java.util.concurrent.TimeoutException: Managed server was not started within 60 s

**Comment by radcortez** [comment]
Hi @joedayz 

Unfortunately I don't have any machine with a win8 env. I did try it with win7 and jdk 8 and it worked fine (except for test failures), but the container started up.

On Mac, it's working. You are having test failures. It's "normal", since tests may not be updated or the applications servers may be doing something different from what's expected in the spec. Anyway, run with the flag -fn so you can complete the build, or -Dmaven.test.skip=true.

**Comment by joedayz** [comment]
Thanks @radcortez

**Comment by radcortez** [comment]
Is this ok? Can we close the issue?

**Comment by joedayz** [comment]
Yes. All is ok!! Thanks
